version: "3.8"

services:
  webhook-listener:
    build:
      context: ..  # Set context to project root
      dockerfile: services/webhook-listener/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AI_SERVICE_URL=http://ai-review:50051
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - ai-review
    networks:
      - gitfox-net

  ai-review:
    build:
      context: ..  # Set context to project root
      dockerfile: services/ai-review/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - gitfox-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  gitfox-net:
    driver: bridge
