version: "3.8"

services:
  webhook-listener:
    build:
      context: ../services/webhook-listener
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AI_SERVICE_URL=http://ai-review:5000/review
    depends_on:
      - ai-review
    networks:
      - gitfox-net

  ai-review:
    build:
      context: ../services/ai-review
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - gitfox-net

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

networks:
  gitfox-net:
    driver: bridge
